version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=rt_tasks
      - POSTGRES_USER=rt_user
      - POSTGRES_PASSWORD=rt_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - POSTGRES_DB=rt_tasks
      - POSTGRES_USER=rt_user
      - POSTGRES_PASSWORD=rt_password   # <- ここを修正
    depends_on:
      - db

volumes:
  db_data:


