version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rt_tasks
      POSTGRES_USER: rt_user
      POSTGRES_PASSWORD: rt_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 core.asgi:application"

    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
      POSTGRES_DB: rt_tasks
      POSTGRES_USER: rt_user
      POSTGRES_PASSWORD: rt_password
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
    depends_on:
      - db

  #frontend:
    #build:
      #context: ./frontend
    #command: sh -c "npm install && npm start"
    #volumes:
      #- ./frontend:/app
    #ports:
      #- "3000:3000"
    #environment:
      #CHOKIDAR_USEPOLLING: "true"  # WindowsやWSLでホットリロードを有効化
    #depends_on:
      #- backend

volumes:
  db_data:



